cd "$(dirname "$0")"
export BUILD_NAME=uz
scons module_bmp_enabled=no module_camera_enabled=no module_csg_enabled=no module_cvtt_enabled=no module_dds_enabled=no module_fbx_enabled=no module_gltf_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_jsonrpc_enabled=no module_ktx_enabled=no module_lightmapper_rd_enabled=no module_mbedtls_enabled=no module_meshoptimizer_enabled=no minimp3_extra_formats=no module_mobile_vr_enabled=no module_mono_enabled=yes module_raycast_enabled=no graphite=no module_tinyexr_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_webp_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_webxr_enabled=no module_xatlas_unwrap_enabled=no module_zip_enabled=no p=macos debug_symbols=yes compiledb=yes deprecated=no no_editor_splash=yes engine_update_check=no arch=x86_64 target=editor
scons module_bmp_enabled=no module_camera_enabled=no module_csg_enabled=no module_cvtt_enabled=no module_dds_enabled=no module_fbx_enabled=no module_gltf_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_jsonrpc_enabled=no module_ktx_enabled=no module_lightmapper_rd_enabled=no module_mbedtls_enabled=no module_meshoptimizer_enabled=no minimp3_extra_formats=no module_mobile_vr_enabled=no module_mono_enabled=yes module_raycast_enabled=no graphite=no module_tinyexr_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_webp_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_webxr_enabled=no module_xatlas_unwrap_enabled=no module_zip_enabled=no p=macos debug_symbols=yes compiledb=yes deprecated=no no_editor_splash=yes engine_update_check=no arch=arm64 target=editor
lipo -create bin/godot.macos.editor.x86_64.mono bin/godot.macos.editor.arm64.mono -output bin/godot.macos.editor.universal.mono
rm bin/godot.macos.editor.x86_64.mono
rm bin/godot.macos.editor.arm64.mono
bin/godot.macos.editor.universal.mono --headless --generate-mono-glue modules/mono/glue
python3 ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=bin
