short_name = "uz_godot"
name = "Team Dichroic Purplion Build of Godot Engine"
major = 4
minor = 3
patch = 0
status = "customized"
module_config = ""
website = "https://godotengine.org"
docs = "latest"
