<Project>
  <Target Name="CopyNupkgToSConsOutputDir" AfterTargets="Pack"
    Condition=" '$(PackageId)' != '' ">
    <PropertyGroup>
      <GodotSourceRootPath>$(MSBuildThisFileDirectory)\..\..\</GodotSourceRootPath>
      <GodotOutputDataDir>$(GodotSourceRootPath)\bin\GodotSharp\</GodotOutputDataDir>
    </PropertyGroup>
    <Copy SourceFiles="$(PackageOutputPath)\$(PackageId).$(PackageVersion).nupkg" DestinationFolder="$(GodotOutputDataDir)Tools\nupkgs\" />
    <Copy Condition=" '$(IncludeSymbols.ToLower())' == 'true' And '$(SymbolPackageFormat)' == 'snupkg' " SourceFiles="$(PackageOutputPath)\$(PackageId).$(PackageVersion).snupkg" DestinationFolder="$(GodotOutputDataDir)Tools\nupkgs\" />
  </Target>
  <Target Name="PushNuGetPackagesToLocalSource" BeforeTargets="Pack"
    Condition=" '$(PackageId)' != '' And '$(PushNuGetToLocalSource)' != '' ">
    <Copy SourceFiles="$(PackageOutputPath)\$(PackageId).$(PackageVersion).nupkg" DestinationFolder="$(PushNuGetToLocalSource)\" />
    <Copy Condition=" '$(IncludeSymbols.ToLower())' == 'true' And '$(SymbolPackageFormat)' == 'snupkg' " SourceFiles="$(PackageOutputPath)\$(PackageId).$(PackageVersion).snupkg" DestinationFolder="$(PushNuGetToLocalSource)\" />
  </Target>
  <Target Name="ClearNuGetLocalPackageCache" BeforeTargets="Pack"
    Condition=" '$(PackageId)' != '' And '$(ClearNuGetLocalCache.ToLower())' == 'true' ">
    <RemoveDir Directories="$(NugetPackageRoot)/$(PackageId.ToLower())/$(PackageVersion)" />
  </Target>
</Project>
